name: Semgrep diff scan

on: pull_request

jobs:
  semgrep-diff:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - name: clone application source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: scan source code
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep scan --error --metrics=off --baseline-commit ${{ github.event.pull_request.base.sha }} --config="p/default"
